### ISSUE TITLE
yolo doesn't give any predictions. Tiny-yolo works well for the same picture

### ISSUE THREAD

**Issue by oprabhu** [thomaspark-pkj/darknet-nnpack#1]
I followed the steps in the README to build this project and its dependencies on a raspberry pi 3 running raspbian with kernel 4.4.50-v7+.
The Test for Tiny-yolo works fine, but the same image for yolo doesnt return any predictions

./darknet detector test cfg/coco.data cfg/yolo.cfg yolo.weights data/person.jpg
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32
    1 max          2 x 2 / 2   416 x 416 x  32   ->   208 x 208 x  32
    2 conv     64  3 x 3 / 1   208 x 208 x  32   ->   208 x 208 x  64
    3 max          2 x 2 / 2   208 x 208 x  64   ->   104 x 104 x  64
    4 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    5 conv     64  1 x 1 / 1   104 x 104 x 128   ->   104 x 104 x  64
    6 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    7 max          2 x 2 / 2   104 x 104 x 128   ->    52 x  52 x 128
    8 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
    9 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128
   10 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
   11 max          2 x 2 / 2    52 x  52 x 256   ->    26 x  26 x 256
   12 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   13 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   14 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   15 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   16 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   17 max          2 x 2 / 2    26 x  26 x 512   ->    13 x  13 x 512
   18 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   19 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   20 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   21 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   22 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   23 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   24 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   25 route  16
   26 reorg              / 2    26 x  26 x 512   ->    13 x  13 x2048
   27 route  26 24
   28 conv   1024  3 x 3 / 1    13 x  13 x3072   ->    13 x  13 x1024
   29 conv    425  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 425
   30 detection
Loading weights from yolo.weights...Done!
data/person.jpg: Predicted in 10302 ms.

~/darknet-nnpack $

**Comment by thomaspark-pkj** [comment]
Recently the YOLO model has been changed. But I have not yet applied it. The weight file on the YOLO homepage is the weight file of the modified model. So it will not work.

Thank you.

**Comment by krishkal** [comment]
Do you know when the modified model will be available? Also, do you have the old weight file available somewhere which will work for your current model? Thanks!

**Comment by thomaspark-pkj** [comment]
It is difficult to tell when it will be possible. I shared old weight file. You can download at below link.
https://drive.google.com/open?id=0B8AJ1FOXWIi5ME4ydlZJYmlyc2s

Thank you.

**Comment by ashwinnair14** [comment]
I have the same problem with tiny yolo.. can any one share the latest tiny yolo cfg and weights file that works?
