### ISSUE TITLE
compile error with darknet-nnpack

### ISSUE THREAD

**Issue by Cv9527** [thomaspark-pkj/darknet-nnpack#2]
when ninja NNPACK-rpi, it encounters error as 
![image](https://cloud.githubusercontent.com/assets/23026189/24576867/1d9c5172-16f6-11e7-8a2e-ef26469b559f.png)

how should I solve the problem? @thomaspark-pkj

**Comment by thomaspark-pkj** [comment]
You can not use the '--enable-rpi' option in ubuntu 16.04.
Please build it in Raspberry PI 3.

Thank you.
