### ISSUE TITLE
dakrnet + compute library from ARM

### ISSUE THREAD

**Issue by Grabber** [thomaspark-pkj/darknet-nnpack#3]
https://developer.arm.com/technologies/compute-library

**Comment by thomaspark-pkj** [comment]
Good!! Thanks for good information.
Will the compute library work on Raspberry Pi 3 ?

**Comment by Grabber** [comment]
In theory yes, have to try.

**Comment by thomaspark-pkj** [comment]
@Grabber Arm compute library does not work in Raspberry pi 3. Do you know who has tried it?

**Comment by Grabber** [comment]
@thomaspark-pkj, I don't think it is mature enough yet. Best move would be to try the GPU approach I posted on the other issue.
