### ISSUE TITLE
# of CPU cores used

### ISSUE THREAD

**Issue by kaishijeng** [thomaspark-pkj/darknet-nnpack#4]
I have an 8 CPU Cores (arm53) and notice darknet-nnpack only uses for 4 instead of all 8 cores.
This may be due to RPI customization. Can you change to use all 8 cores to speed up more?

Thanks,

**Comment by thomaspark-pkj** [comment]
Yon can change the code 'pthreadpool_create(4)' in detector.c to 'pthreadpool_create(8)'.

Thank you

**Comment by kaishijeng** [comment]
I will make a change and try it out

Thanks,.

**Comment by kaishijeng** [comment]
It works
Thanks
