### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by kyo0105** [thomaspark-pkj/darknet-nnpack#46]
Detected root directory: /home/pi/NNPACK-darknet
/usr/local/lib/python2.7/dist-packages/confu/manifest.py:36: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  manifest_yaml = yaml.load(manifest_text)
Configuring dependency pthreadpool
Configuring dependency fxdiv
Configuring dependency googletest
Configuring dependency googlebenchmark
Traceback (most recent call last):
  File "./configure.py", line 396, in <module>
    main(sys.argv[1:]).generate()
  File "./configure.py", line 36, in main
    (build.deps.pthreadpool, build.deps.fxdiv, build.deps.fp16): any,
  File "/usr/local/lib/python2.7/dist-packages/confu/builds/deps.py", line 48, in __getattr__
    config = configure.main(["--target", self._target])
  File "/home/pi/NNPACK-darknet/deps/pthreadpool/configure.py", line 20, in main
    build.static_library("pthreadpool", [build.cc(src) for src in sources])
  File "/usr/local/lib/python2.7/dist-packages/confu/builds/unix.py", line 72, in cc
    return self._compile("cc", source_path)
  File "/usr/local/lib/python2.7/dist-packages/confu/builds/unix.py", line 56, in _compile
    source_path = validate_source_path(source_path, self.source_dir)
  File "/usr/local/lib/python2.7/dist-packages/confu/validators.py", line 67, in validate_source_path
    .format(source_path=source_path))
ValueError: Specified source file /home/pi/NNPACK-darknet/deps/pthreadpool/src/threadpool-legacy.c does not exist

**Comment by bileki** [comment]
The pthreadpool has been updated and this file has been renamed.
Back some versions of the repository. It worked for me

cd NNPACK-darknet/deps/pthreadpool/
git checkout 5b41aa6060588e26fd25ace6dc4afccfd4793997

and then

python ./configure.py --backend auto

**Comment by znsoftm** [comment]
for to compile nnpack, you could use cmake to build it rather than confu. The author told me he has abandoned confu.

**Comment by Shivankit99** [comment]
> for to compile nnpack, you could use cmake to build it rather than confu. The author told me he has abandoned confu.

could you help on how to build with cmake , im new to linux so unable to do it

**Comment by Shivankit99** [comment]
Could you help me with building NNPACK with CMAKE .. i am new to
raspberrypi and would really appreciate some help .
