### ISSUE TITLE
nnp_convolution_inference call is not compatible with the latest NNPACK SW

### ISSUE THREAD

**Issue by kaishijeng** [thomaspark-pkj/darknet-nnpack#5]
I have an A57 (aarch64) board running on ubuntu 16.04 and can use the latest NNPACK. However, darknet-nnpack has the following error:

gcc  -DNNPACK -DARM_NEON -Wall  -O3 -DNNPACK -DARM_NEON -O3 -funsafe-math-optimizations -ftree-vectorize -c ./src/convolutional_layer.c -o obj/convolutional_layer.o
./src/convolutional_layer.c: In function 'forward_convolutional_layer_nnpack':
./src/convolutional_layer.c:438:2: error: too few arguments to function 'nnp_convolution_inference'
  nnp_convolution_inference(
  ^

Do you have a plan to update darknet-nnpack to the latest NNPACK SW?

Thanks,

**Comment by thomaspark-pkj** [comment]
Latest NNPACK is not compatible to darknet-nnpack. Use NNPACK-rpi instead of latest NNPACK. Refer to the README.md for details.
I have a plan to update NNPACK-rpi and darknet-nnpack in a few weeks.

Thanks,
