### ISSUE TITLE
NNpack build issue on raspberry pi 4 

### ISSUE THREAD

**Issue by HaroldSP** [thomaspark-pkj/darknet-nnpack#52]
![image](https://user-images.githubusercontent.com/55085987/80981860-3280ce80-8e33-11ea-8a51-130f823ac215.png)
Following your guide on raspberry pi 4, but NNpack won't build.

Can you help me please with that issue?

**Comment by iand111** [comment]
I am running into the same problem. I think the issues revolves around building pthreadpool with confu, as this is apparently this build is deprecated (https://github.com/Maratyszcza/pthreadpool/issues/8). I have not found a way around this.

**Comment by angmorpri** [comment]
I don't know if it may help, but I solved an error similar to that one following the steps [here](https://github.com/digitalbrain79/darknet-nnpack/issues/53#issuecomment-627878333).

**Comment by HaroldSP** [comment]
@iand111 
Thanks everyone, finally it works!
Here's the small [wiki]( https://github.com/HaroldSP/Harold/wiki/4.-Installing-darknet-nnpack-to-run-YOLOv3-on-Raspberry-pi-4) that I've written.
