### ISSUE TITLE
use a customized gemm

### ISSUE THREAD

**Issue by ydzhang12345** [thomaspark-pkj/darknet-nnpack#7]
Hi,

Your work is amazing and really help us a lot! Great job!

For our application, we need to have a customized gemm (e.g. quantized gemm), may I ask if it is possible to modify directly on the gemm.c and gemm.h part of your work? Many thanks!

Ben

**Comment by thomaspark-pkj** [comment]
Yes. However, like NNPACK, you should use the define statement inside the Makefile.

Thanks,
